name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libdbus
      run: sudo apt-get install -y libdbus-1-3 libdbus-1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose --no-default-features
        cargo test --verbose
        cargo test --verbose --all-features
    - name: Run demo tests
      run: |
        cd demos/shared && cargo test --verbose
        cd ../..
        cd demos/docking && cargo test --verbose
        cd ../.. 
        cd demos/sparse && cargo test --verbose
        cd ../..
        cd demos/spreadsheet && cargo test --verbose
        cd ../..
